import {env} from "cloudflare:workers";
import {cookies} from "next/headers";
export const AUTH_COOKIE="sgt_access",REFRESH_COOKIE="sgt_refresh";
export function authConfig(){const url=String(env.SUPABASE_URL??""),key=String(env.SUPABASE_PUBLISHABLE_KEY??"");return url.startsWith("https://")&&key?{url:url.replace(/\/$/,""),key}:null;}
export async function authRequest(path:string,body?:unknown,token?:string,method?:string){const c=authConfig();if(!c)throw new Error("Login por e-mail ainda não configurado.");return fetch(`${c.url}/auth/v1/${path}`,{method:method??(body?"POST":"GET"),headers:{apikey:c.key,"content-type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{}),cache:"no-store"});}
export async function providerUser(token:string){try{const r=await authRequest("user",undefined,token);if(!r.ok)return null;const u=await r.json() as any;if(!u.id||!u.email||!u.email_confirmed_at)return null;return {id:`supabase:${u.id}`,email:u.email,fullName:typeof u.user_metadata?.name==="string"?u.user_metadata.name:null,displayName:u.user_metadata?.name||u.email};}catch{return null}}
export async function getProviderUser(){const jar=await cookies();const token=jar.get(AUTH_COOKIE)?.value;return token?providerUser(token):null;}
export function writeSession(response:Response,session:any){if(!session.access_token||!session.refresh_token)throw new Error("Sessão inválida.");response.headers.append("Set-Cookie",`${AUTH_COOKIE}=${encodeURIComponent(session.access_token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${Math.min(Number(session.expires_in)||3600,86400)}`);response.headers.append("Set-Cookie",`${REFRESH_COOKIE}=${encodeURIComponent(session.refresh_token)}; Path=/central/api/auth; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000`);response.headers.set("Cache-Control","no-store");return response;}
export function clearSession(response:Response){response.headers.append("Set-Cookie",`${AUTH_COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`);response.headers.append("Set-Cookie",`${REFRESH_COOKIE}=; Path=/central/api/auth; HttpOnly; Secure; SameSite=Lax; Max-Age=0`);return response;}
