import { approvalNotice, registrationLinks } from "./registration";

const escapeHtml = (value: string) => value.replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
const link = (url: string, label: string) => `<a href="${url}" style="color:#1459ba;text-decoration:underline;font-weight:bold">${label}</a>`;
const button = (url: string, label: string) => `<table role="presentation" cellspacing="0" cellpadding="0" style="margin-top:18px"><tr><td bgcolor="#1764d7" style="border-radius:4px"><a href="${url}" style="display:inline-block;padding:15px 22px;color:#ffffff;font:700 15px Arial,sans-serif;text-decoration:none">${label} &rarr;</a></td></tr></table>`;
const section = (number: string, title: string, body: string) => `<tr><td style="padding:26px 28px;border-bottom:1px solid #e2e7ee"><p style="margin:0 0 10px;color:#1764d7;font-size:11px;font-weight:bold;letter-spacing:2px">ETAPA ${number}</p><h2 style="margin:0 0 12px;font-size:22px;color:#101722">${title}</h2>${body}</td></tr>`;

export function welcomeEmailHtml(name: string) {
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bem-vindo à Speed GT Brasil</title></head>
<body style="margin:0;padding:0;background:#e9edf2;font-family:Arial,Helvetica,sans-serif;color:#425066;font-size:15px;line-height:1.65">
<div style="display:none;max-height:0;overflow:hidden;mso-hide:all">Cadastro recebido! Veja os próximos passos para entrar na comunidade Speed GT Brasil.</div>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" bgcolor="#e9edf2"><tr><td align="center" style="padding:24px 10px">
<table role="presentation" width="600" cellspacing="0" cellpadding="0" style="width:100%;max-width:600px;background:#ffffff">
<tr><td bgcolor="#101722" style="padding:28px;border-top:5px solid #1764d7"><img src="cid:speedgt-logo" width="104" height="104" alt="Speed GT Brasil" style="display:block;border:0;border-radius:8px"><p style="margin:24px 0 8px;color:#8ebaff;font-size:11px;letter-spacing:3px;font-weight:bold">SPEED GT BRASIL &nbsp; / &nbsp; <span style="white-space:nowrap">GRAN TURISMO 7</span></p><h1 style="margin:0;color:#ffffff;font-size:34px;line-height:1.12;font-weight:900;font-style:italic;text-transform:uppercase">Seu lugar no grid<br>começa aqui.</h1><p style="margin:18px 0 0;color:#c1cbd9">Cadastro recebido. Agora, prepare-se para os próximos passos.</p></td></tr>
<tr><td style="padding:28px 28px 8px"><p style="margin:0 0 12px;font-size:20px;font-weight:bold;color:#101722">Olá, ${escapeHtml(name)}!</p><p style="margin:0 0 20px">Bem-vindo à Speed GT Brasil. Reunimos abaixo tudo o que você precisa para acompanhar a comunidade e preparar sua estreia.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td bgcolor="#edf4ff" style="padding:18px;border-left:4px solid #1764d7"><strong style="color:#143c78">Seu cadastro está em análise</strong><p style="margin:8px 0 0;font-size:14px">${approvalNotice}</p></td></tr></table></td></tr>
${section("01", "Entre no nosso paddock", `<p style="margin:0">Solicite sua entrada no grupo do WhatsApp para acompanhar os avisos e conversar com os pilotos. A liberação depende da aprovação da administração.</p>${button(registrationLinks.whatsapp, "Solicitar entrada no WhatsApp")}`)}
${section("02", "Acompanhe a comunidade", `<p style="margin:0">Bastidores, novidades e momentos das nossas disputas no Instagram.</p><p style="margin:12px 0 0">${link(registrationLinks.instagram, "Seguir @speedgtbr")}</p>`)}
${section("03", "Prepare seu SimGrid", `<p style="margin:0">Usaremos o SimGrid nas inscrições dos campeonatos. Você pode preparar sua conta agora e aguardar as orientações do grupo para se inscrever.</p>${button(registrationLinks.video, "Assistir ao vídeo tutorial")}<ol style="padding-left:22px;margin:22px 0 0"><li style="margin-bottom:12px">Crie uma conta no ${link("https://discord.com/register", "Discord")} ou na ${link("https://store.steampowered.com/join/", "Steam")}, se ainda não tiver. Conclua as verificações do serviço escolhido; basta uma das duas contas.</li><li style="margin-bottom:12px">Abra o ${link("https://www.thesimgrid.com", "SimGrid")}, escolha <strong>Login or Register</strong>, entre com Discord ou Steam e autorize a conexão.</li><li style="margin-bottom:12px">Complete seu perfil e confira sua <strong>ID da PSN</strong>, usando a mesma informada no cadastro da Speed GT Brasil.</li><li style="margin-bottom:12px">Abra a ${link(registrationLinks.simgrid, "comunidade Speed GT Brasil")} e clique em <strong>Follow Community</strong> para seguir.</li><li>Aguarde as orientações da administração para entrar no campeonato adequado.</li></ol>`)}
${section("04", "Ajude a manter a comunidade na pista", `<p style="margin:0">O apoio é opcional e não interfere na análise do seu cadastro.</p><p style="margin:12px 0 0">${link(registrationLinks.support, "Conhecer as formas de apoiar")}</p>`)}
<tr><td bgcolor="#101722" style="padding:26px 28px"><p style="margin:0;color:#ffffff;font-size:22px;font-weight:bold;font-style:italic">Nos vemos na pista!</p><p style="margin:8px 0 0;color:#a9b6c8;font-size:13px">Speed GT Brasil · Comunidade de automobilismo virtual</p><p style="margin:12px 0 0;color:#a9b6c8;font-size:13px">Precisa de ajuda? Responda a este e-mail.</p></td></tr>
</table><p style="max-width:560px;margin:18px auto 0;color:#68758a;font-size:11px">Você recebeu esta mensagem porque preencheu o cadastro da Speed GT Brasil.</p>
</td></tr></table></body></html>`;
}
