name = "speedgtbr"
pages_build_output_dir = "dist-pages"
compatibility_date = "2026-09-08"
compatibility_flags = ["nodejs_compat"]

[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_name = "speedgtbr-central-preview"
database_id = "14f2c59a-224b-471b-a398-b331dfeb78fe"
migrations_dir = "central/drizzle"

[env.preview.vars]
REGISTRATION_EMAIL_FROM = "Speed GT Brasil <administracao@speedgtbrasil.com.br>"
REGISTRATION_EMAIL_REPLY_TO = "speedgtbr@gmail.com"
ACCESS_TEAM_DOMAIN = "purple-butterfly-b461.cloudflareaccess.com"
ACCESS_AUD = "8b3aa31522a4d544a12ff7a826ede0fe95f2c7b54d1b970d82f0fa1b542e024e"

[env.production]

[[env.production.d1_databases]]
binding = "DB"
database_name = "speedgtbr-central-production"
database_id = "1ee66e07-82f9-4ed3-8ad8-27a7a3dffa88"
migrations_dir = "central/drizzle"

[env.production.vars]
REGISTRATION_EMAIL_FROM = "Speed GT Brasil <administracao@speedgtbrasil.com.br>"
REGISTRATION_EMAIL_REPLY_TO = "speedgtbr@gmail.com"
REQUIRE_ADMIN_ACCESS = "true"
