CREATE TABLE `atividade_contexto` (
	`id` integer PRIMARY KEY NOT NULL,
	`usuario` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE `atividades` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`usuario` text NOT NULL,
	`data_hora` text NOT NULL,
	`acao` text NOT NULL,
	`entidade` text NOT NULL,
	`identificador` text NOT NULL,
	`anterior` text,
	`novo` text
);
--> statement-breakpoint
CREATE INDEX `idx_atividades_data` ON `atividades` (`data_hora`);--> statement-breakpoint
CREATE TABLE `classificacoes_oficiais` (
	`temporada_id` text PRIMARY KEY NOT NULL,
	`encerrada_em` text NOT NULL,
	`usuario` text NOT NULL,
	`dados` text NOT NULL,
	FOREIGN KEY (`temporada_id`) REFERENCES `temporadas`(`id`) ON UPDATE no action ON DELETE restrict
);
--> statement-breakpoint
CREATE TABLE `livro_caixa` (
	`id` text PRIMARY KEY NOT NULL,
	`natureza` text NOT NULL,
	`categoria` text NOT NULL,
	`descricao` text NOT NULL,
	`valor` integer NOT NULL,
	`data` text NOT NULL,
	`responsavel` text NOT NULL,
	`comprovante` text,
	`piloto_id` text,
	`temporada_id` text,
	FOREIGN KEY (`piloto_id`) REFERENCES `pilotos`(`id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`temporada_id`) REFERENCES `temporadas`(`id`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "ck_livro_natureza" CHECK("livro_caixa"."natureza" IN ('receita','despesa')),
	CONSTRAINT "ck_livro_valor" CHECK("livro_caixa"."valor">0)
);
--> statement-breakpoint
CREATE INDEX `idx_livro_temporada_data` ON `livro_caixa` (`temporada_id`,`data`);--> statement-breakpoint
ALTER TABLE `temporadas` ADD `ciclo` text DEFAULT 'ativa' NOT NULL;--> statement-breakpoint
ALTER TABLE `temporadas` ADD `encerrada_em` text;--> statement-breakpoint
ALTER TABLE `temporadas` ADD `temporada_anterior_id` text;
--> statement-breakpoint
CREATE TRIGGER audit_pilotos_insert AFTER INSERT ON pilotos BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'criou','pilotos',CAST(NEW.id AS TEXT),NULL,json_object('id',NEW.id,'apelido',NEW.apelido,'nome_completo',NEW.nome_completo,'psn',NEW.psn,'simgrid',NEW.simgrid,'simgrid_url',NEW.simgrid_url,'whatsapp',NEW.whatsapp,'email',NEW.email,'cidade',NEW.cidade,'uf',NEW.uf,'volante_ou_controle',NEW.volante_ou_controle,'perfil_pilotagem',NEW.perfil_pilotagem,'disponibilidade',NEW.disponibilidade,'carro_preferido',NEW.carro_preferido,'pista_citada',NEW.pista_citada,'relacoes',NEW.relacoes,'curiosidade',NEW.curiosidade,'observacoes_adm',NEW.observacoes_adm,'ativo',NEW.ativo,'cadastro_status',NEW.cadastro_status,'data_nascimento',NEW.data_nascimento,'data_entrada',NEW.data_entrada,'arquivado_em',NEW.arquivado_em,'motivo_arquivamento',NEW.motivo_arquivamento)); END;
--> statement-breakpoint
CREATE TRIGGER audit_pilotos_update AFTER UPDATE ON pilotos BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'alterou','pilotos',CAST(NEW.id AS TEXT),json_object('id',OLD.id,'apelido',OLD.apelido,'nome_completo',OLD.nome_completo,'psn',OLD.psn,'simgrid',OLD.simgrid,'simgrid_url',OLD.simgrid_url,'whatsapp',OLD.whatsapp,'email',OLD.email,'cidade',OLD.cidade,'uf',OLD.uf,'volante_ou_controle',OLD.volante_ou_controle,'perfil_pilotagem',OLD.perfil_pilotagem,'disponibilidade',OLD.disponibilidade,'carro_preferido',OLD.carro_preferido,'pista_citada',OLD.pista_citada,'relacoes',OLD.relacoes,'curiosidade',OLD.curiosidade,'observacoes_adm',OLD.observacoes_adm,'ativo',OLD.ativo,'cadastro_status',OLD.cadastro_status,'data_nascimento',OLD.data_nascimento,'data_entrada',OLD.data_entrada,'arquivado_em',OLD.arquivado_em,'motivo_arquivamento',OLD.motivo_arquivamento),json_object('id',NEW.id,'apelido',NEW.apelido,'nome_completo',NEW.nome_completo,'psn',NEW.psn,'simgrid',NEW.simgrid,'simgrid_url',NEW.simgrid_url,'whatsapp',NEW.whatsapp,'email',NEW.email,'cidade',NEW.cidade,'uf',NEW.uf,'volante_ou_controle',NEW.volante_ou_controle,'perfil_pilotagem',NEW.perfil_pilotagem,'disponibilidade',NEW.disponibilidade,'carro_preferido',NEW.carro_preferido,'pista_citada',NEW.pista_citada,'relacoes',NEW.relacoes,'curiosidade',NEW.curiosidade,'observacoes_adm',NEW.observacoes_adm,'ativo',NEW.ativo,'cadastro_status',NEW.cadastro_status,'data_nascimento',NEW.data_nascimento,'data_entrada',NEW.data_entrada,'arquivado_em',NEW.arquivado_em,'motivo_arquivamento',NEW.motivo_arquivamento)); END;
--> statement-breakpoint
CREATE TRIGGER audit_pilotos_delete AFTER DELETE ON pilotos BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'excluiu','pilotos',CAST(OLD.id AS TEXT),json_object('id',OLD.id,'apelido',OLD.apelido,'nome_completo',OLD.nome_completo,'psn',OLD.psn,'simgrid',OLD.simgrid,'simgrid_url',OLD.simgrid_url,'whatsapp',OLD.whatsapp,'email',OLD.email,'cidade',OLD.cidade,'uf',OLD.uf,'volante_ou_controle',OLD.volante_ou_controle,'perfil_pilotagem',OLD.perfil_pilotagem,'disponibilidade',OLD.disponibilidade,'carro_preferido',OLD.carro_preferido,'pista_citada',OLD.pista_citada,'relacoes',OLD.relacoes,'curiosidade',OLD.curiosidade,'observacoes_adm',OLD.observacoes_adm,'ativo',OLD.ativo,'cadastro_status',OLD.cadastro_status,'data_nascimento',OLD.data_nascimento,'data_entrada',OLD.data_entrada,'arquivado_em',OLD.arquivado_em,'motivo_arquivamento',OLD.motivo_arquivamento),NULL); END;
--> statement-breakpoint
CREATE TRIGGER audit_fila_insert AFTER INSERT ON fila BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'criou','fila',CAST(NEW.id AS TEXT),NULL,json_object('id',NEW.id,'apelido',NEW.apelido,'nome_completo',NEW.nome_completo,'psn',NEW.psn,'simgrid',NEW.simgrid,'whatsapp',NEW.whatsapp,'cidade',NEW.cidade,'uf',NEW.uf,'email',NEW.email,'corridas_4fun',NEW.corridas_4fun,'conduta',NEW.conduta,'pronto_para_serie',NEW.pronto_para_serie,'simgrid_url',NEW.simgrid_url,'volante_ou_controle',NEW.volante_ou_controle,'perfil_pilotagem',NEW.perfil_pilotagem,'disponibilidade',NEW.disponibilidade,'carro_preferido',NEW.carro_preferido,'pista_citada',NEW.pista_citada,'relacoes',NEW.relacoes,'curiosidade',NEW.curiosidade,'observacoes_adm',NEW.observacoes_adm,'ativo',NEW.ativo,'cadastro_status',NEW.cadastro_status,'promovido_para_piloto_id',NEW.promovido_para_piloto_id,'data_nascimento',NEW.data_nascimento,'data_entrada',NEW.data_entrada,'arquivado_em',NEW.arquivado_em,'motivo_arquivamento',NEW.motivo_arquivamento)); END;
--> statement-breakpoint
CREATE TRIGGER audit_fila_update AFTER UPDATE ON fila BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'alterou','fila',CAST(NEW.id AS TEXT),json_object('id',OLD.id,'apelido',OLD.apelido,'nome_completo',OLD.nome_completo,'psn',OLD.psn,'simgrid',OLD.simgrid,'whatsapp',OLD.whatsapp,'cidade',OLD.cidade,'uf',OLD.uf,'email',OLD.email,'corridas_4fun',OLD.corridas_4fun,'conduta',OLD.conduta,'pronto_para_serie',OLD.pronto_para_serie,'simgrid_url',OLD.simgrid_url,'volante_ou_controle',OLD.volante_ou_controle,'perfil_pilotagem',OLD.perfil_pilotagem,'disponibilidade',OLD.disponibilidade,'carro_preferido',OLD.carro_preferido,'pista_citada',OLD.pista_citada,'relacoes',OLD.relacoes,'curiosidade',OLD.curiosidade,'observacoes_adm',OLD.observacoes_adm,'ativo',OLD.ativo,'cadastro_status',OLD.cadastro_status,'promovido_para_piloto_id',OLD.promovido_para_piloto_id,'data_nascimento',OLD.data_nascimento,'data_entrada',OLD.data_entrada,'arquivado_em',OLD.arquivado_em,'motivo_arquivamento',OLD.motivo_arquivamento),json_object('id',NEW.id,'apelido',NEW.apelido,'nome_completo',NEW.nome_completo,'psn',NEW.psn,'simgrid',NEW.simgrid,'whatsapp',NEW.whatsapp,'cidade',NEW.cidade,'uf',NEW.uf,'email',NEW.email,'corridas_4fun',NEW.corridas_4fun,'conduta',NEW.conduta,'pronto_para_serie',NEW.pronto_para_serie,'simgrid_url',NEW.simgrid_url,'volante_ou_controle',NEW.volante_ou_controle,'perfil_pilotagem',NEW.perfil_pilotagem,'disponibilidade',NEW.disponibilidade,'carro_preferido',NEW.carro_preferido,'pista_citada',NEW.pista_citada,'relacoes',NEW.relacoes,'curiosidade',NEW.curiosidade,'observacoes_adm',NEW.observacoes_adm,'ativo',NEW.ativo,'cadastro_status',NEW.cadastro_status,'promovido_para_piloto_id',NEW.promovido_para_piloto_id,'data_nascimento',NEW.data_nascimento,'data_entrada',NEW.data_entrada,'arquivado_em',NEW.arquivado_em,'motivo_arquivamento',NEW.motivo_arquivamento)); END;
--> statement-breakpoint
CREATE TRIGGER audit_fila_delete AFTER DELETE ON fila BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'excluiu','fila',CAST(OLD.id AS TEXT),json_object('id',OLD.id,'apelido',OLD.apelido,'nome_completo',OLD.nome_completo,'psn',OLD.psn,'simgrid',OLD.simgrid,'whatsapp',OLD.whatsapp,'cidade',OLD.cidade,'uf',OLD.uf,'email',OLD.email,'corridas_4fun',OLD.corridas_4fun,'conduta',OLD.conduta,'pronto_para_serie',OLD.pronto_para_serie,'simgrid_url',OLD.simgrid_url,'volante_ou_controle',OLD.volante_ou_controle,'perfil_pilotagem',OLD.perfil_pilotagem,'disponibilidade',OLD.disponibilidade,'carro_preferido',OLD.carro_preferido,'pista_citada',OLD.pista_citada,'relacoes',OLD.relacoes,'curiosidade',OLD.curiosidade,'observacoes_adm',OLD.observacoes_adm,'ativo',OLD.ativo,'cadastro_status',OLD.cadastro_status,'promovido_para_piloto_id',OLD.promovido_para_piloto_id,'data_nascimento',OLD.data_nascimento,'data_entrada',OLD.data_entrada,'arquivado_em',OLD.arquivado_em,'motivo_arquivamento',OLD.motivo_arquivamento),NULL); END;
--> statement-breakpoint
CREATE TRIGGER audit_formularios_pendentes_insert AFTER INSERT ON formularios_pendentes BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'criou','formularios_pendentes',CAST(NEW.id AS TEXT),NULL,json_object('id',NEW.id,'criado_em',NEW.criado_em,'nome_completo',NEW.nome_completo,'psn',NEW.psn,'simgrid',NEW.simgrid,'simgrid_url',NEW.simgrid_url,'whatsapp',NEW.whatsapp,'email',NEW.email,'cidade',NEW.cidade,'uf',NEW.uf,'volante_ou_controle',NEW.volante_ou_controle,'perfil_pilotagem',NEW.perfil_pilotagem,'disponibilidade',NEW.disponibilidade,'carro_preferido',NEW.carro_preferido,'pista_citada',NEW.pista_citada,'status',NEW.status,'revisado_em',NEW.revisado_em,'destino_tipo',NEW.destino_tipo,'destino_id',NEW.destino_id,'data_nascimento',NEW.data_nascimento,'curiosidade',NEW.curiosidade)); END;
--> statement-breakpoint
CREATE TRIGGER audit_formularios_pendentes_update AFTER UPDATE ON formularios_pendentes BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'alterou','formularios_pendentes',CAST(NEW.id AS TEXT),json_object('id',OLD.id,'criado_em',OLD.criado_em,'nome_completo',OLD.nome_completo,'psn',OLD.psn,'simgrid',OLD.simgrid,'simgrid_url',OLD.simgrid_url,'whatsapp',OLD.whatsapp,'email',OLD.email,'cidade',OLD.cidade,'uf',OLD.uf,'volante_ou_controle',OLD.volante_ou_controle,'perfil_pilotagem',OLD.perfil_pilotagem,'disponibilidade',OLD.disponibilidade,'carro_preferido',OLD.carro_preferido,'pista_citada',OLD.pista_citada,'status',OLD.status,'revisado_em',OLD.revisado_em,'destino_tipo',OLD.destino_tipo,'destino_id',OLD.destino_id,'data_nascimento',OLD.data_nascimento,'curiosidade',OLD.curiosidade),json_object('id',NEW.id,'criado_em',NEW.criado_em,'nome_completo',NEW.nome_completo,'psn',NEW.psn,'simgrid',NEW.simgrid,'simgrid_url',NEW.simgrid_url,'whatsapp',NEW.whatsapp,'email',NEW.email,'cidade',NEW.cidade,'uf',NEW.uf,'volante_ou_controle',NEW.volante_ou_controle,'perfil_pilotagem',NEW.perfil_pilotagem,'disponibilidade',NEW.disponibilidade,'carro_preferido',NEW.carro_preferido,'pista_citada',NEW.pista_citada,'status',NEW.status,'revisado_em',NEW.revisado_em,'destino_tipo',NEW.destino_tipo,'destino_id',NEW.destino_id,'data_nascimento',NEW.data_nascimento,'curiosidade',NEW.curiosidade)); END;
--> statement-breakpoint
CREATE TRIGGER audit_formularios_pendentes_delete AFTER DELETE ON formularios_pendentes BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'excluiu','formularios_pendentes',CAST(OLD.id AS TEXT),json_object('id',OLD.id,'criado_em',OLD.criado_em,'nome_completo',OLD.nome_completo,'psn',OLD.psn,'simgrid',OLD.simgrid,'simgrid_url',OLD.simgrid_url,'whatsapp',OLD.whatsapp,'email',OLD.email,'cidade',OLD.cidade,'uf',OLD.uf,'volante_ou_controle',OLD.volante_ou_controle,'perfil_pilotagem',OLD.perfil_pilotagem,'disponibilidade',OLD.disponibilidade,'carro_preferido',OLD.carro_preferido,'pista_citada',OLD.pista_citada,'status',OLD.status,'revisado_em',OLD.revisado_em,'destino_tipo',OLD.destino_tipo,'destino_id',OLD.destino_id,'data_nascimento',OLD.data_nascimento,'curiosidade',OLD.curiosidade),NULL); END;
--> statement-breakpoint
CREATE TRIGGER audit_inscricoes_insert AFTER INSERT ON inscricoes BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'criou','inscricoes',CAST(NEW.temporada_id AS TEXT)||'/'||CAST(NEW.piloto_id AS TEXT),NULL,json_object('temporada_id',NEW.temporada_id,'piloto_id',NEW.piloto_id,'serie',NEW.serie,'situacao',NEW.situacao,'saida_em',NEW.saida_em,'motivo_saida',NEW.motivo_saida,'previsao_volta',NEW.previsao_volta,'pagamento_isento',NEW.pagamento_isento)); END;
--> statement-breakpoint
CREATE TRIGGER audit_inscricoes_update AFTER UPDATE ON inscricoes BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'alterou','inscricoes',CAST(NEW.temporada_id AS TEXT)||'/'||CAST(NEW.piloto_id AS TEXT),json_object('temporada_id',OLD.temporada_id,'piloto_id',OLD.piloto_id,'serie',OLD.serie,'situacao',OLD.situacao,'saida_em',OLD.saida_em,'motivo_saida',OLD.motivo_saida,'previsao_volta',OLD.previsao_volta,'pagamento_isento',OLD.pagamento_isento),json_object('temporada_id',NEW.temporada_id,'piloto_id',NEW.piloto_id,'serie',NEW.serie,'situacao',NEW.situacao,'saida_em',NEW.saida_em,'motivo_saida',NEW.motivo_saida,'previsao_volta',NEW.previsao_volta,'pagamento_isento',NEW.pagamento_isento)); END;
--> statement-breakpoint
CREATE TRIGGER audit_inscricoes_delete AFTER DELETE ON inscricoes BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'excluiu','inscricoes',CAST(OLD.temporada_id AS TEXT)||'/'||CAST(OLD.piloto_id AS TEXT),json_object('temporada_id',OLD.temporada_id,'piloto_id',OLD.piloto_id,'serie',OLD.serie,'situacao',OLD.situacao,'saida_em',OLD.saida_em,'motivo_saida',OLD.motivo_saida,'previsao_volta',OLD.previsao_volta,'pagamento_isento',OLD.pagamento_isento),NULL); END;
--> statement-breakpoint
CREATE TRIGGER audit_corridas_insert AFTER INSERT ON corridas BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'criou','corridas',CAST(NEW.temporada_id AS TEXT)||'/'||CAST(NEW.etapa AS TEXT)||'/'||CAST(NEW.piloto_id AS TEXT),NULL,json_object('temporada_id',NEW.temporada_id,'etapa',NEW.etapa,'piloto_id',NEW.piloto_id,'confirmou',NEW.confirmou,'compareceu',NEW.compareceu,'falta_justificada',NEW.falta_justificada,'posicao_final',NEW.posicao_final,'volta_mais_rapida',NEW.volta_mais_rapida,'punicao',NEW.punicao,'abandono_motivo',NEW.abandono_motivo,'observacao',NEW.observacao,'pontos',NEW.pontos,'carro',NEW.carro,'fabricante',NEW.fabricante,'origem_carro',NEW.origem_carro,'suplente',NEW.suplente,'pontos_suplente',NEW.pontos_suplente)); END;
--> statement-breakpoint
CREATE TRIGGER audit_corridas_update AFTER UPDATE ON corridas BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'alterou','corridas',CAST(NEW.temporada_id AS TEXT)||'/'||CAST(NEW.etapa AS TEXT)||'/'||CAST(NEW.piloto_id AS TEXT),json_object('temporada_id',OLD.temporada_id,'etapa',OLD.etapa,'piloto_id',OLD.piloto_id,'confirmou',OLD.confirmou,'compareceu',OLD.compareceu,'falta_justificada',OLD.falta_justificada,'posicao_final',OLD.posicao_final,'volta_mais_rapida',OLD.volta_mais_rapida,'punicao',OLD.punicao,'abandono_motivo',OLD.abandono_motivo,'observacao',OLD.observacao,'pontos',OLD.pontos,'carro',OLD.carro,'fabricante',OLD.fabricante,'origem_carro',OLD.origem_carro,'suplente',OLD.suplente,'pontos_suplente',OLD.pontos_suplente),json_object('temporada_id',NEW.temporada_id,'etapa',NEW.etapa,'piloto_id',NEW.piloto_id,'confirmou',NEW.confirmou,'compareceu',NEW.compareceu,'falta_justificada',NEW.falta_justificada,'posicao_final',NEW.posicao_final,'volta_mais_rapida',NEW.volta_mais_rapida,'punicao',NEW.punicao,'abandono_motivo',NEW.abandono_motivo,'observacao',NEW.observacao,'pontos',NEW.pontos,'carro',NEW.carro,'fabricante',NEW.fabricante,'origem_carro',NEW.origem_carro,'suplente',NEW.suplente,'pontos_suplente',NEW.pontos_suplente)); END;
--> statement-breakpoint
CREATE TRIGGER audit_corridas_delete AFTER DELETE ON corridas BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'excluiu','corridas',CAST(OLD.temporada_id AS TEXT)||'/'||CAST(OLD.etapa AS TEXT)||'/'||CAST(OLD.piloto_id AS TEXT),json_object('temporada_id',OLD.temporada_id,'etapa',OLD.etapa,'piloto_id',OLD.piloto_id,'confirmou',OLD.confirmou,'compareceu',OLD.compareceu,'falta_justificada',OLD.falta_justificada,'posicao_final',OLD.posicao_final,'volta_mais_rapida',OLD.volta_mais_rapida,'punicao',OLD.punicao,'abandono_motivo',OLD.abandono_motivo,'observacao',OLD.observacao,'pontos',OLD.pontos,'carro',OLD.carro,'fabricante',OLD.fabricante,'origem_carro',OLD.origem_carro,'suplente',OLD.suplente,'pontos_suplente',OLD.pontos_suplente),NULL); END;
--> statement-breakpoint
CREATE TRIGGER audit_calendario_insert AFTER INSERT ON calendario BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'criou','calendario',CAST(NEW.temporada_id AS TEXT)||'/'||CAST(NEW.etapa AS TEXT),NULL,json_object('temporada_id',NEW.temporada_id,'etapa',NEW.etapa,'pista',NEW.pista,'classe_ou_formato',NEW.classe_ou_formato,'duracao',NEW.duracao,'data',NEW.data,'multiplicador',NEW.multiplicador,'observacao',NEW.observacao,'regra_carro',NEW.regra_carro,'carro_padrao',NEW.carro_padrao,'fabricante_padrao',NEW.fabricante_padrao)); END;
--> statement-breakpoint
CREATE TRIGGER audit_calendario_update AFTER UPDATE ON calendario BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'alterou','calendario',CAST(NEW.temporada_id AS TEXT)||'/'||CAST(NEW.etapa AS TEXT),json_object('temporada_id',OLD.temporada_id,'etapa',OLD.etapa,'pista',OLD.pista,'classe_ou_formato',OLD.classe_ou_formato,'duracao',OLD.duracao,'data',OLD.data,'multiplicador',OLD.multiplicador,'observacao',OLD.observacao,'regra_carro',OLD.regra_carro,'carro_padrao',OLD.carro_padrao,'fabricante_padrao',OLD.fabricante_padrao),json_object('temporada_id',NEW.temporada_id,'etapa',NEW.etapa,'pista',NEW.pista,'classe_ou_formato',NEW.classe_ou_formato,'duracao',NEW.duracao,'data',NEW.data,'multiplicador',NEW.multiplicador,'observacao',NEW.observacao,'regra_carro',NEW.regra_carro,'carro_padrao',NEW.carro_padrao,'fabricante_padrao',NEW.fabricante_padrao)); END;
--> statement-breakpoint
CREATE TRIGGER audit_calendario_delete AFTER DELETE ON calendario BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'excluiu','calendario',CAST(OLD.temporada_id AS TEXT)||'/'||CAST(OLD.etapa AS TEXT),json_object('temporada_id',OLD.temporada_id,'etapa',OLD.etapa,'pista',OLD.pista,'classe_ou_formato',OLD.classe_ou_formato,'duracao',OLD.duracao,'data',OLD.data,'multiplicador',OLD.multiplicador,'observacao',OLD.observacao,'regra_carro',OLD.regra_carro,'carro_padrao',OLD.carro_padrao,'fabricante_padrao',OLD.fabricante_padrao),NULL); END;
--> statement-breakpoint
CREATE TRIGGER audit_divisoes_insert AFTER INSERT ON divisoes BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'criou','divisoes',CAST(NEW.id AS TEXT),NULL,json_object('id',NEW.id,'temporada_id',NEW.temporada_id,'codigo',NEW.codigo,'nome',NEW.nome,'cor',NEW.cor,'ordem',NEW.ordem,'regra_carro',NEW.regra_carro,'carro_padrao',NEW.carro_padrao,'fabricante_padrao',NEW.fabricante_padrao,'status',NEW.status,'arquivada_em',NEW.arquivada_em,'motivo_arquivamento',NEW.motivo_arquivamento,'whatsapp_group_url',NEW.whatsapp_group_url,'limite_pilotos',NEW.limite_pilotos,'data_inicio',NEW.data_inicio,'frequencia_dias',NEW.frequencia_dias,'aberto_suplentes',NEW.aberto_suplentes)); END;
--> statement-breakpoint
CREATE TRIGGER audit_divisoes_update AFTER UPDATE ON divisoes BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'alterou','divisoes',CAST(NEW.id AS TEXT),json_object('id',OLD.id,'temporada_id',OLD.temporada_id,'codigo',OLD.codigo,'nome',OLD.nome,'cor',OLD.cor,'ordem',OLD.ordem,'regra_carro',OLD.regra_carro,'carro_padrao',OLD.carro_padrao,'fabricante_padrao',OLD.fabricante_padrao,'status',OLD.status,'arquivada_em',OLD.arquivada_em,'motivo_arquivamento',OLD.motivo_arquivamento,'whatsapp_group_url',OLD.whatsapp_group_url,'limite_pilotos',OLD.limite_pilotos,'data_inicio',OLD.data_inicio,'frequencia_dias',OLD.frequencia_dias,'aberto_suplentes',OLD.aberto_suplentes),json_object('id',NEW.id,'temporada_id',NEW.temporada_id,'codigo',NEW.codigo,'nome',NEW.nome,'cor',NEW.cor,'ordem',NEW.ordem,'regra_carro',NEW.regra_carro,'carro_padrao',NEW.carro_padrao,'fabricante_padrao',NEW.fabricante_padrao,'status',NEW.status,'arquivada_em',NEW.arquivada_em,'motivo_arquivamento',NEW.motivo_arquivamento,'whatsapp_group_url',NEW.whatsapp_group_url,'limite_pilotos',NEW.limite_pilotos,'data_inicio',NEW.data_inicio,'frequencia_dias',NEW.frequencia_dias,'aberto_suplentes',NEW.aberto_suplentes)); END;
--> statement-breakpoint
CREATE TRIGGER audit_divisoes_delete AFTER DELETE ON divisoes BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'excluiu','divisoes',CAST(OLD.id AS TEXT),json_object('id',OLD.id,'temporada_id',OLD.temporada_id,'codigo',OLD.codigo,'nome',OLD.nome,'cor',OLD.cor,'ordem',OLD.ordem,'regra_carro',OLD.regra_carro,'carro_padrao',OLD.carro_padrao,'fabricante_padrao',OLD.fabricante_padrao,'status',OLD.status,'arquivada_em',OLD.arquivada_em,'motivo_arquivamento',OLD.motivo_arquivamento,'whatsapp_group_url',OLD.whatsapp_group_url,'limite_pilotos',OLD.limite_pilotos,'data_inicio',OLD.data_inicio,'frequencia_dias',OLD.frequencia_dias,'aberto_suplentes',OLD.aberto_suplentes),NULL); END;
--> statement-breakpoint
CREATE TRIGGER audit_temporadas_insert AFTER INSERT ON temporadas BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'criou','temporadas',CAST(NEW.id AS TEXT),NULL,json_object('id',NEW.id,'nome',NEW.nome,'ativa',NEW.ativa,'total_etapas',NEW.total_etapas,'pilotos_por_serie',NEW.pilotos_por_serie,'tipo_evento',NEW.tipo_evento,'gera_classificacao',NEW.gera_classificacao,'regra_carro',NEW.regra_carro,'carro_padrao',NEW.carro_padrao,'fabricante_padrao',NEW.fabricante_padrao,'status',NEW.status,'arquivada_em',NEW.arquivada_em,'motivo_arquivamento',NEW.motivo_arquivamento,'whatsapp_group_url',NEW.whatsapp_group_url,'ciclo',NEW.ciclo,'encerrada_em',NEW.encerrada_em,'temporada_anterior_id',NEW.temporada_anterior_id)); END;
--> statement-breakpoint
CREATE TRIGGER audit_temporadas_update AFTER UPDATE ON temporadas BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'alterou','temporadas',CAST(NEW.id AS TEXT),json_object('id',OLD.id,'nome',OLD.nome,'ativa',OLD.ativa,'total_etapas',OLD.total_etapas,'pilotos_por_serie',OLD.pilotos_por_serie,'tipo_evento',OLD.tipo_evento,'gera_classificacao',OLD.gera_classificacao,'regra_carro',OLD.regra_carro,'carro_padrao',OLD.carro_padrao,'fabricante_padrao',OLD.fabricante_padrao,'status',OLD.status,'arquivada_em',OLD.arquivada_em,'motivo_arquivamento',OLD.motivo_arquivamento,'whatsapp_group_url',OLD.whatsapp_group_url,'ciclo',OLD.ciclo,'encerrada_em',OLD.encerrada_em,'temporada_anterior_id',OLD.temporada_anterior_id),json_object('id',NEW.id,'nome',NEW.nome,'ativa',NEW.ativa,'total_etapas',NEW.total_etapas,'pilotos_por_serie',NEW.pilotos_por_serie,'tipo_evento',NEW.tipo_evento,'gera_classificacao',NEW.gera_classificacao,'regra_carro',NEW.regra_carro,'carro_padrao',NEW.carro_padrao,'fabricante_padrao',NEW.fabricante_padrao,'status',NEW.status,'arquivada_em',NEW.arquivada_em,'motivo_arquivamento',NEW.motivo_arquivamento,'whatsapp_group_url',NEW.whatsapp_group_url,'ciclo',NEW.ciclo,'encerrada_em',NEW.encerrada_em,'temporada_anterior_id',NEW.temporada_anterior_id)); END;
--> statement-breakpoint
CREATE TRIGGER audit_temporadas_delete AFTER DELETE ON temporadas BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'excluiu','temporadas',CAST(OLD.id AS TEXT),json_object('id',OLD.id,'nome',OLD.nome,'ativa',OLD.ativa,'total_etapas',OLD.total_etapas,'pilotos_por_serie',OLD.pilotos_por_serie,'tipo_evento',OLD.tipo_evento,'gera_classificacao',OLD.gera_classificacao,'regra_carro',OLD.regra_carro,'carro_padrao',OLD.carro_padrao,'fabricante_padrao',OLD.fabricante_padrao,'status',OLD.status,'arquivada_em',OLD.arquivada_em,'motivo_arquivamento',OLD.motivo_arquivamento,'whatsapp_group_url',OLD.whatsapp_group_url,'ciclo',OLD.ciclo,'encerrada_em',OLD.encerrada_em,'temporada_anterior_id',OLD.temporada_anterior_id),NULL); END;
--> statement-breakpoint
CREATE TRIGGER audit_caixa_insert AFTER INSERT ON caixa BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'criou','caixa',CAST(NEW.id AS TEXT),NULL,json_object('id',NEW.id,'temporada_id',NEW.temporada_id,'data',NEW.data,'piloto_id',NEW.piloto_id,'nome',NEW.nome,'tipo',NEW.tipo,'valor',NEW.valor,'vai_para_medalha',NEW.vai_para_medalha,'observacao',NEW.observacao)); END;
--> statement-breakpoint
CREATE TRIGGER audit_caixa_update AFTER UPDATE ON caixa BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'alterou','caixa',CAST(NEW.id AS TEXT),json_object('id',OLD.id,'temporada_id',OLD.temporada_id,'data',OLD.data,'piloto_id',OLD.piloto_id,'nome',OLD.nome,'tipo',OLD.tipo,'valor',OLD.valor,'vai_para_medalha',OLD.vai_para_medalha,'observacao',OLD.observacao),json_object('id',NEW.id,'temporada_id',NEW.temporada_id,'data',NEW.data,'piloto_id',NEW.piloto_id,'nome',NEW.nome,'tipo',NEW.tipo,'valor',NEW.valor,'vai_para_medalha',NEW.vai_para_medalha,'observacao',NEW.observacao)); END;
--> statement-breakpoint
CREATE TRIGGER audit_caixa_delete AFTER DELETE ON caixa BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'excluiu','caixa',CAST(OLD.id AS TEXT),json_object('id',OLD.id,'temporada_id',OLD.temporada_id,'data',OLD.data,'piloto_id',OLD.piloto_id,'nome',OLD.nome,'tipo',OLD.tipo,'valor',OLD.valor,'vai_para_medalha',OLD.vai_para_medalha,'observacao',OLD.observacao),NULL); END;
--> statement-breakpoint
CREATE TRIGGER audit_caixa_configuracao_insert AFTER INSERT ON caixa_configuracao BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'criou','caixa_configuracao',CAST(NEW.temporada_id AS TEXT),NULL,json_object('temporada_id',NEW.temporada_id,'medalha_individual',NEW.medalha_individual,'medalha_temporada',NEW.medalha_temporada,'frete_individual',NEW.frete_individual,'frete_temporada',NEW.frete_temporada,'saldo_caixa',NEW.saldo_caixa)); END;
--> statement-breakpoint
CREATE TRIGGER audit_caixa_configuracao_update AFTER UPDATE ON caixa_configuracao BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'alterou','caixa_configuracao',CAST(NEW.temporada_id AS TEXT),json_object('temporada_id',OLD.temporada_id,'medalha_individual',OLD.medalha_individual,'medalha_temporada',OLD.medalha_temporada,'frete_individual',OLD.frete_individual,'frete_temporada',OLD.frete_temporada,'saldo_caixa',OLD.saldo_caixa),json_object('temporada_id',NEW.temporada_id,'medalha_individual',NEW.medalha_individual,'medalha_temporada',NEW.medalha_temporada,'frete_individual',NEW.frete_individual,'frete_temporada',NEW.frete_temporada,'saldo_caixa',NEW.saldo_caixa)); END;
--> statement-breakpoint
CREATE TRIGGER audit_caixa_configuracao_delete AFTER DELETE ON caixa_configuracao BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'excluiu','caixa_configuracao',CAST(OLD.temporada_id AS TEXT),json_object('temporada_id',OLD.temporada_id,'medalha_individual',OLD.medalha_individual,'medalha_temporada',OLD.medalha_temporada,'frete_individual',OLD.frete_individual,'frete_temporada',OLD.frete_temporada,'saldo_caixa',OLD.saldo_caixa),NULL); END;
--> statement-breakpoint
CREATE TRIGGER audit_usuarios_acessos_insert AFTER INSERT ON usuarios_acessos BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'criou','usuarios_acessos',CAST(NEW.id AS TEXT),NULL,json_object('id',NEW.id,'account_user_id',NEW.account_user_id,'email',NEW.email,'nome',NEW.nome,'papel',NEW.papel,'serie',NEW.serie,'ativo',NEW.ativo)); END;
--> statement-breakpoint
CREATE TRIGGER audit_usuarios_acessos_update AFTER UPDATE ON usuarios_acessos BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'alterou','usuarios_acessos',CAST(NEW.id AS TEXT),json_object('id',OLD.id,'account_user_id',OLD.account_user_id,'email',OLD.email,'nome',OLD.nome,'papel',OLD.papel,'serie',OLD.serie,'ativo',OLD.ativo),json_object('id',NEW.id,'account_user_id',NEW.account_user_id,'email',NEW.email,'nome',NEW.nome,'papel',NEW.papel,'serie',NEW.serie,'ativo',NEW.ativo)); END;
--> statement-breakpoint
CREATE TRIGGER audit_usuarios_acessos_delete AFTER DELETE ON usuarios_acessos BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'excluiu','usuarios_acessos',CAST(OLD.id AS TEXT),json_object('id',OLD.id,'account_user_id',OLD.account_user_id,'email',OLD.email,'nome',OLD.nome,'papel',OLD.papel,'serie',OLD.serie,'ativo',OLD.ativo),NULL); END;
--> statement-breakpoint
CREATE TRIGGER audit_solicitacoes_acesso_insert AFTER INSERT ON solicitacoes_acesso BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'criou','solicitacoes_acesso',CAST(NEW.id AS TEXT),NULL,json_object('id',NEW.id,'account_user_id',NEW.account_user_id,'email',NEW.email,'nome',NEW.nome,'status',NEW.status,'criado_em',NEW.criado_em,'revisado_em',NEW.revisado_em,'revisado_por',NEW.revisado_por)); END;
--> statement-breakpoint
CREATE TRIGGER audit_solicitacoes_acesso_update AFTER UPDATE ON solicitacoes_acesso BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'alterou','solicitacoes_acesso',CAST(NEW.id AS TEXT),json_object('id',OLD.id,'account_user_id',OLD.account_user_id,'email',OLD.email,'nome',OLD.nome,'status',OLD.status,'criado_em',OLD.criado_em,'revisado_em',OLD.revisado_em,'revisado_por',OLD.revisado_por),json_object('id',NEW.id,'account_user_id',NEW.account_user_id,'email',NEW.email,'nome',NEW.nome,'status',NEW.status,'criado_em',NEW.criado_em,'revisado_em',NEW.revisado_em,'revisado_por',NEW.revisado_por)); END;
--> statement-breakpoint
CREATE TRIGGER audit_solicitacoes_acesso_delete AFTER DELETE ON solicitacoes_acesso BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'excluiu','solicitacoes_acesso',CAST(OLD.id AS TEXT),json_object('id',OLD.id,'account_user_id',OLD.account_user_id,'email',OLD.email,'nome',OLD.nome,'status',OLD.status,'criado_em',OLD.criado_em,'revisado_em',OLD.revisado_em,'revisado_por',OLD.revisado_por),NULL); END;
--> statement-breakpoint
CREATE TRIGGER audit_livro_caixa_insert AFTER INSERT ON livro_caixa BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'criou','livro_caixa',CAST(NEW.id AS TEXT),NULL,json_object('id',NEW.id,'natureza',NEW.natureza,'categoria',NEW.categoria,'descricao',NEW.descricao,'valor',NEW.valor,'data',NEW.data,'responsavel',NEW.responsavel,'comprovante',NEW.comprovante,'piloto_id',NEW.piloto_id,'temporada_id',NEW.temporada_id)); END;
--> statement-breakpoint
CREATE TRIGGER audit_livro_caixa_update AFTER UPDATE ON livro_caixa BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'alterou','livro_caixa',CAST(NEW.id AS TEXT),json_object('id',OLD.id,'natureza',OLD.natureza,'categoria',OLD.categoria,'descricao',OLD.descricao,'valor',OLD.valor,'data',OLD.data,'responsavel',OLD.responsavel,'comprovante',OLD.comprovante,'piloto_id',OLD.piloto_id,'temporada_id',OLD.temporada_id),json_object('id',NEW.id,'natureza',NEW.natureza,'categoria',NEW.categoria,'descricao',NEW.descricao,'valor',NEW.valor,'data',NEW.data,'responsavel',NEW.responsavel,'comprovante',NEW.comprovante,'piloto_id',NEW.piloto_id,'temporada_id',NEW.temporada_id)); END;
--> statement-breakpoint
CREATE TRIGGER audit_livro_caixa_delete AFTER DELETE ON livro_caixa BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'excluiu','livro_caixa',CAST(OLD.id AS TEXT),json_object('id',OLD.id,'natureza',OLD.natureza,'categoria',OLD.categoria,'descricao',OLD.descricao,'valor',OLD.valor,'data',OLD.data,'responsavel',OLD.responsavel,'comprovante',OLD.comprovante,'piloto_id',OLD.piloto_id,'temporada_id',OLD.temporada_id),NULL); END;
--> statement-breakpoint
CREATE TRIGGER audit_classificacoes_oficiais_insert AFTER INSERT ON classificacoes_oficiais BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'criou','classificacoes_oficiais',CAST(NEW.temporada_id AS TEXT),NULL,json_object('temporada_id',NEW.temporada_id,'encerrada_em',NEW.encerrada_em,'usuario',NEW.usuario,'dados',NEW.dados)); END;
--> statement-breakpoint
CREATE TRIGGER audit_classificacoes_oficiais_update AFTER UPDATE ON classificacoes_oficiais BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'alterou','classificacoes_oficiais',CAST(NEW.temporada_id AS TEXT),json_object('temporada_id',OLD.temporada_id,'encerrada_em',OLD.encerrada_em,'usuario',OLD.usuario,'dados',OLD.dados),json_object('temporada_id',NEW.temporada_id,'encerrada_em',NEW.encerrada_em,'usuario',NEW.usuario,'dados',NEW.dados)); END;
--> statement-breakpoint
CREATE TRIGGER audit_classificacoes_oficiais_delete AFTER DELETE ON classificacoes_oficiais BEGIN INSERT INTO atividades(usuario,data_hora,acao,entidade,identificador,anterior,novo) VALUES(COALESCE((SELECT usuario FROM atividade_contexto WHERE id=1),'Sistema'),strftime('%Y-%m-%dT%H:%M:%fZ','now'),'excluiu','classificacoes_oficiais',CAST(OLD.temporada_id AS TEXT),json_object('temporada_id',OLD.temporada_id,'encerrada_em',OLD.encerrada_em,'usuario',OLD.usuario,'dados',OLD.dados),NULL); END;
--> statement-breakpoint
CREATE TRIGGER freeze_corridas_insert BEFORE INSERT ON corridas WHEN EXISTS(SELECT 1 FROM classificacoes_oficiais WHERE temporada_id=NEW.temporada_id) BEGIN SELECT RAISE(ABORT,'Temporada encerrada: histórico esportivo protegido.'); END;
--> statement-breakpoint
CREATE TRIGGER freeze_corridas_update BEFORE UPDATE ON corridas WHEN EXISTS(SELECT 1 FROM classificacoes_oficiais WHERE temporada_id=NEW.temporada_id) OR EXISTS(SELECT 1 FROM classificacoes_oficiais WHERE temporada_id=OLD.temporada_id) BEGIN SELECT RAISE(ABORT,'Temporada encerrada: histórico esportivo protegido.'); END;
--> statement-breakpoint
CREATE TRIGGER freeze_corridas_delete BEFORE DELETE ON corridas WHEN EXISTS(SELECT 1 FROM classificacoes_oficiais WHERE temporada_id=OLD.temporada_id) BEGIN SELECT RAISE(ABORT,'Temporada encerrada: histórico esportivo protegido.'); END;
--> statement-breakpoint
CREATE TRIGGER freeze_inscricoes_insert BEFORE INSERT ON inscricoes WHEN EXISTS(SELECT 1 FROM classificacoes_oficiais WHERE temporada_id=NEW.temporada_id) BEGIN SELECT RAISE(ABORT,'Temporada encerrada: histórico esportivo protegido.'); END;
--> statement-breakpoint
CREATE TRIGGER freeze_inscricoes_update BEFORE UPDATE ON inscricoes WHEN EXISTS(SELECT 1 FROM classificacoes_oficiais WHERE temporada_id=NEW.temporada_id) OR EXISTS(SELECT 1 FROM classificacoes_oficiais WHERE temporada_id=OLD.temporada_id) BEGIN SELECT RAISE(ABORT,'Temporada encerrada: histórico esportivo protegido.'); END;
--> statement-breakpoint
CREATE TRIGGER freeze_inscricoes_delete BEFORE DELETE ON inscricoes WHEN EXISTS(SELECT 1 FROM classificacoes_oficiais WHERE temporada_id=OLD.temporada_id) BEGIN SELECT RAISE(ABORT,'Temporada encerrada: histórico esportivo protegido.'); END;
--> statement-breakpoint
CREATE TRIGGER freeze_calendario_insert BEFORE INSERT ON calendario WHEN EXISTS(SELECT 1 FROM classificacoes_oficiais WHERE temporada_id=NEW.temporada_id) BEGIN SELECT RAISE(ABORT,'Temporada encerrada: histórico esportivo protegido.'); END;
--> statement-breakpoint
CREATE TRIGGER freeze_calendario_update BEFORE UPDATE ON calendario WHEN EXISTS(SELECT 1 FROM classificacoes_oficiais WHERE temporada_id=NEW.temporada_id) OR EXISTS(SELECT 1 FROM classificacoes_oficiais WHERE temporada_id=OLD.temporada_id) BEGIN SELECT RAISE(ABORT,'Temporada encerrada: histórico esportivo protegido.'); END;
--> statement-breakpoint
CREATE TRIGGER freeze_calendario_delete BEFORE DELETE ON calendario WHEN EXISTS(SELECT 1 FROM classificacoes_oficiais WHERE temporada_id=OLD.temporada_id) BEGIN SELECT RAISE(ABORT,'Temporada encerrada: histórico esportivo protegido.'); END;
--> statement-breakpoint
CREATE TRIGGER freeze_divisoes_insert BEFORE INSERT ON divisoes WHEN EXISTS(SELECT 1 FROM classificacoes_oficiais WHERE temporada_id=NEW.temporada_id) BEGIN SELECT RAISE(ABORT,'Temporada encerrada: histórico esportivo protegido.'); END;
--> statement-breakpoint
CREATE TRIGGER freeze_divisoes_update BEFORE UPDATE ON divisoes WHEN EXISTS(SELECT 1 FROM classificacoes_oficiais WHERE temporada_id=NEW.temporada_id) OR EXISTS(SELECT 1 FROM classificacoes_oficiais WHERE temporada_id=OLD.temporada_id) BEGIN SELECT RAISE(ABORT,'Temporada encerrada: histórico esportivo protegido.'); END;
--> statement-breakpoint
CREATE TRIGGER freeze_divisoes_delete BEFORE DELETE ON divisoes WHEN EXISTS(SELECT 1 FROM classificacoes_oficiais WHERE temporada_id=OLD.temporada_id) BEGIN SELECT RAISE(ABORT,'Temporada encerrada: histórico esportivo protegido.'); END;
--> statement-breakpoint
CREATE TRIGGER freeze_official_update BEFORE UPDATE ON classificacoes_oficiais BEGIN SELECT RAISE(ABORT,'Classificação oficial imutável.'); END;
--> statement-breakpoint
CREATE TRIGGER freeze_official_delete BEFORE DELETE ON classificacoes_oficiais BEGIN SELECT RAISE(ABORT,'Classificação oficial imutável.'); END;
--> statement-breakpoint
CREATE TRIGGER freeze_temporada BEFORE UPDATE ON temporadas WHEN EXISTS(SELECT 1 FROM classificacoes_oficiais WHERE temporada_id=OLD.id) AND (NEW.id IS NOT OLD.id OR NEW.total_etapas IS NOT OLD.total_etapas OR NEW.gera_classificacao IS NOT OLD.gera_classificacao OR NEW.tipo_evento IS NOT OLD.tipo_evento OR NEW.pilotos_por_serie IS NOT OLD.pilotos_por_serie OR NEW.nome IS NOT OLD.nome OR NEW.ciclo NOT IN ('encerrada','arquivada') OR NEW.ativa<>0) BEGIN SELECT RAISE(ABORT,'A temporada encerrada não pode ter sua estrutura esportiva alterada.'); END;
--> statement-breakpoint
CREATE TRIGGER validate_season_cycle BEFORE UPDATE OF ciclo ON temporadas WHEN NEW.ciclo NOT IN ('planejada','ativa','encerrada','arquivada') OR (NEW.ciclo='encerrada' AND NOT EXISTS(SELECT 1 FROM classificacoes_oficiais WHERE temporada_id=NEW.id)) BEGIN SELECT RAISE(ABORT,'Ciclo de temporada inválido.'); END;
--> statement-breakpoint
CREATE TRIGGER unique_next_season BEFORE INSERT ON temporadas WHEN NEW.temporada_anterior_id IS NOT NULL AND EXISTS(SELECT 1 FROM temporadas WHERE temporada_anterior_id=NEW.temporada_anterior_id) BEGIN SELECT RAISE(ABORT,'A próxima temporada já foi criada.'); END;
--> statement-breakpoint
CREATE TRIGGER race_active_season BEFORE INSERT ON corridas WHEN (SELECT ciclo FROM temporadas WHERE id=NEW.temporada_id)<>'ativa' BEGIN SELECT RAISE(ABORT,'Ative a temporada antes de lançar resultados.'); END;
--> statement-breakpoint
CREATE TRIGGER race_active_season_update BEFORE UPDATE ON corridas WHEN (SELECT ciclo FROM temporadas WHERE id=NEW.temporada_id)<>'ativa' BEGIN SELECT RAISE(ABORT,'Temporada indisponível para resultados.'); END;
