"use client";
import {useEffect,useState} from "react";
export function AuthScreen({configured,account=false}:{configured:boolean;account?:boolean}){
 const [mode,setMode]=useState(account?"password":"login"),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{const hash=new URLSearchParams(window.location.hash.slice(1));const access_token=hash.get("access_token"),refresh_token=hash.get("refresh_token");if(!access_token||!refresh_token){if(configured&&!account&&!new URLSearchParams(window.location.search).has("expired"))window.location.replace("/central/api/auth/refresh");return;}history.replaceState(null,"",window.location.pathname);setBusy(true);fetch("/central/api/auth/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({access_token,refresh_token})}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);setMessage("E-mail confirmado. Você pode definir uma nova senha ou acessar a Central.")}).catch(e=>setError(e.message)).finally(()=>setBusy(false));},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");setMessage("");try{const r=await fetch(`/central/api/auth/${mode}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});const j=await r.json();if(!r.ok)throw new Error(j.error);if(mode==="login")window.location.assign("/central");else setMessage(j.message)}catch(e){setError(e instanceof Error?e.message:"Não foi possível concluir.")}finally{setBusy(false)}}
 return <main className="flex min-h-dvh items-center justify-center p-5"><section className="w-full max-w-md rounded-lg border border-border bg-card p-6 sm:p-8"><img src="/central/brand/speed-gt-brasil.png" alt="Speed GT Brasil" className="mb-6 h-20 w-20 object-contain"/><p className="text-sm text-primary">Central da liga</p><h1 className="mt-2 text-3xl">{mode==="signup"?"Criar conta":mode==="recover"?"Recuperar senha":mode==="password"?"Minha conta":"Entrar"}</h1>
 {!configured?<div className="mt-5 space-y-4"><p className="text-sm leading-6 text-muted-foreground">O acesso por e-mail será liberado após a configuração da autenticação. Continue com o acesso atual.</p><a className="central-action w-full" href="/central" target="_top">Entrar com Cloudflare Access</a></div>:<><form className="mt-5 space-y-4" onSubmit={submit}>{mode==="signup"&&<label className="central-field">Nome<input required name="name" autoComplete="name" maxLength={120}/></label>}{mode!=="password"&&<label className="central-field">E-mail<input required name="email" type="email" autoComplete="email"/></label>}{mode!=="recover"&&<label className="central-field">{mode==="password"?"Nova senha":"Senha"}<input required name="password" type="password" minLength={12} autoComplete={mode==="login"?"current-password":"new-password"}/><span className="text-xs text-muted-foreground">Pelo menos 12 caracteres.</span></label>}<button disabled={busy} className="central-action w-full">{busy?"Aguarde…":mode==="signup"?"Solicitar acesso":mode==="recover"?"Enviar recuperação":mode==="password"?"Alterar senha":"Entrar"}</button></form><div className="mt-4 flex flex-wrap gap-3 text-sm">{mode!=="login"&&<button className="min-h-11 text-primary" onClick={()=>{setMode("login");setError("");setMessage("")}}>Voltar ao login</button>}{mode==="login"&&<><button className="min-h-11 text-primary" onClick={()=>setMode("signup")}>Criar conta</button><button className="min-h-11 text-muted-foreground" onClick={()=>setMode("recover")}>Esqueci minha senha</button></>}{account&&<a className="min-h-11 py-3 text-primary" href="/central">Acessar a Central</a>}</div></>}
 {error&&<p role="alert" className="mt-4 text-sm text-red-300">{error}</p>}{message&&<p role="status" className="mt-4 rounded border border-green-900 bg-green-950/30 p-3 text-sm leading-6 text-green-300">{message}</p>}
 <div className="mt-6 border-t border-border pt-5 text-sm text-muted-foreground"><p>Quer correr na Speed GT?</p><a className="mt-1 inline-flex min-h-11 items-center text-primary underline" href="/cadastro">Abrir formulário público de piloto</a></div></section></main>
}
