"use client";
import {useEffect,useState} from "react";
import type {RaceCompetition} from "@/db/races";
import type {PilotListItem} from "@/db/pilots";
type Entry={id:string;origem:string;natureza:string;categoria:string;descricao:string;valor:number;data:string;responsavel:string;comprovante:string|null;piloto_id:string|null;temporada_id:string|null};
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v/100);
export function LedgerScreen({competitions,pilots}:{competitions:RaceCompetition[];pilots:PilotListItem[]}){
 const [entries,setEntries]=useState<Entry[]>([]),[scope,setScope]=useState(""),[query,setQuery]=useState(""),[open,setOpen]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 async function load(){try{const r=await fetch("/central/api/livro-caixa"),j=await r.json();if(!r.ok)throw new Error(j.error);setEntries(j.entries);setLoaded(true)}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar.")}}useEffect(()=>{void load()},[]);
 const scoped=entries.filter(e=>!scope||e.temporada_id===scope),visible=scoped.filter(e=>`${e.categoria} ${e.descricao} ${e.responsavel}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())),income=scoped.filter(e=>e.natureza==="receita").reduce((a,e)=>a+e.valor,0),expense=scoped.filter(e=>e.natureza==="despesa").reduce((a,e)=>a+e.valor,0);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const form=e.currentTarget,b=Object.fromEntries(new FormData(form));const value=String(b.valor).replace(/\./g,"").replace(",",".");try{const r=await fetch("/central/api/livro-caixa",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...b,valor:Math.round(Number(value)*100)})}),j=await r.json();if(!r.ok)throw new Error(j.error);await load();setOpen(false)}catch(e){setError(e instanceof Error?e.message:"Falha ao salvar.")}finally{setBusy(false)}}
 return <main className="mx-auto max-w-6xl px-3 py-5 pb-32 md:px-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-primary">Financeiro da liga</p><h1>Livro-caixa</h1></div><button className="central-action" onClick={()=>setOpen(v=>!v)}>{open?"Fechar lançamento":"Nova receita ou despesa"}</button></div>
 <label className="central-field mt-5 max-w-md">Visão do caixa<select value={scope} onChange={e=>setScope(e.target.value)}><option value="">Caixa Geral · todas as temporadas</option>{competitions.map(c=><option value={c.id} key={c.id}>{c.nome}</option>)}</select></label>
 {error&&<p role="alert" className="my-4 text-red-300">{error}</p>}
 {open&&<form onSubmit={save} className="central-panel mt-5"><h2>Novo lançamento</h2><p className="mt-2 text-sm text-muted-foreground">Para registrar a inscrição de um piloto, use a aba Inscrições e pagamentos.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><Field title="Tipo"><select name="natureza"><option value="receita">Receita</option><option value="despesa">Despesa</option></select></Field><Field title="Categoria"><input required name="categoria" list="categorias"/><datalist id="categorias">{["Medalhas","Hospedagem","Serviços","Premiação","Patrocínio","Doação","Outros"].map(c=><option key={c} value={c}/>)}</datalist></Field><Field title="Descrição"><input required name="descricao" maxLength={500}/></Field><Field title="Valor (R$)"><input required name="valor" inputMode="decimal" pattern="[0-9.]+(,[0-9]{1,2})?" placeholder="0,00"/></Field><Field title="Data"><input required type="date" name="data" defaultValue={new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo"}).format(new Date())}/></Field><Field title="Temporada (opcional)"><select name="temporadaId" defaultValue={scope}><option value="">Sem vínculo · caixa geral</option>{competitions.map(c=><option value={c.id} key={c.id}>{c.nome}</option>)}</select></Field><Field title="Piloto (opcional)"><select name="pilotoId"><option value="">Sem vínculo com piloto</option>{pilots.map(p=><option key={p.id} value={p.id}>{p.apelido}</option>)}</select></Field><Field title="Comprovante (link HTTPS, opcional)"><input type="url" name="comprovante" placeholder="https://…"/></Field></div><p className="mt-3 text-sm text-muted-foreground">O responsável será registrado automaticamente pela sua conta.</p><button disabled={busy} className="central-action mt-4">{busy?"Salvando…":"Salvar lançamento"}</button></form>}
 <section className="my-5 grid gap-3 sm:grid-cols-3">{[["Receitas",income,"text-green-300"],["Despesas",expense,"text-red-300"],["Saldo",income-expense,"text-primary"]].map(([label,value,tone])=><article key={String(label)} className="central-panel"><p className="text-sm text-muted-foreground">{label}</p><strong className={`font-data mt-2 block text-2xl ${tone}`}>{loaded?money(Number(value)):"—"}</strong></article>)}</section>
 <section className="central-panel"><div className="flex flex-wrap items-center justify-between gap-3"><h2>Lançamentos</h2><label className="central-field"><span className="sr-only">Buscar lançamento</span><input placeholder="Buscar descrição, categoria ou autor" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>{!loaded?<p className="py-5">Carregando…</p>:!visible.length?<p className="py-5 text-muted-foreground">Nenhum lançamento nesta seleção.</p>:visible.map(e=><article key={`${e.origem}-${e.id}`} className="grid gap-3 border-b border-border py-4 sm:grid-cols-[110px_1fr_auto]"><time className="text-sm text-muted-foreground">{e.data.split("-").reverse().join("/")}</time><div><strong>{e.descricao}</strong><p className="mt-1 text-sm text-muted-foreground">{e.categoria} · {e.temporada_id?competitions.find(c=>c.id===e.temporada_id)?.nome:"Caixa geral"}</p><p className="text-xs text-muted-foreground">{e.responsavel}</p>{e.comprovante&&<a className="text-sm text-primary underline" href={e.comprovante} target="_blank" rel="noopener noreferrer">Ver comprovante</a>}</div><div className="flex items-center gap-3"><strong className={`font-data ${e.natureza==="despesa"?"text-red-300":"text-green-300"}`}>{e.natureza==="despesa"?"−":"+"}{money(e.valor)}</strong>{e.origem==="livro"&&<button className="min-h-11 px-2 text-sm text-red-300" disabled={busy} onClick={async()=>{if(!window.confirm(`Excluir ${e.descricao} (${money(e.valor)})? A exclusão ficará no log.`))return;setBusy(true);try{const r=await fetch("/central/api/livro-caixa",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:e.id})});if(!r.ok)throw new Error("Falha ao excluir.");await load()}catch(e){setError(e instanceof Error?e.message:"Falha ao excluir.")}finally{setBusy(false)}}}>Excluir</button>}</div></article>)}</section>
 </main>
}
function Field({title,children}:{title:string;children:React.ReactNode}){return <label className="central-field">{title}{children}</label>}
