"use client";
import {useState} from "react";
import type {getRaceEntryData} from "@/db/races";
import type {OfficialRow} from "@/db/season-lifecycle";
type Props={data:any;raceData:Awaited<ReturnType<typeof getRaceEntryData>>;onAction:(b:any)=>Promise<boolean>};
export function SeasonWizard({data,raceData,onAction}:Props){
 const [revision,setRevision]=useState<number|undefined>();
 const [source,setSource]=useState(""),[rows,setRows]=useState<(OfficialRow&{motivo:string;included:boolean;suggested?:string})[]>([]),[mode,setMode]=useState(""),[name,setName]=useState(""),[confirm,setConfirm]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[add,setAdd]=useState("");
 const divisions=raceData.divisoes.filter(d=>d.temporadaId===source&&d.status!=="cancelada").sort((a,b)=>a.ordem-b.ordem);
 async function open(id:string,kind:string){setBusy(true);setError("");try{const r=await fetch(`/central/api/admin?temporadaId=${encodeURIComponent(id)}`);const j=await r.json();if(!r.ok)throw new Error(j.error);if(kind==="nova"&&!j.oficial)throw new Error("Encerre a temporada anterior primeiro.");setSource(id);setRevision(j.revision);setMode(kind);setConfirm("");setRows(j.rows.map((r:OfficialRow)=>({...r,motivo:"",included:true,suggested:r.destino})));setName("")}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar.")}finally{setBusy(false)}}
 const patch=(id:string,v:any)=>setRows(rs=>rs.map(r=>r.pilotoId===id?{...r,...v}:r));
 const excluded=rows.filter(r=>!r.included);
 const candidates=raceData.pilotosDisponiveis.filter(p=>p.kind==="piloto"&&!rows.some(r=>r.pilotoId===p.id));
 const invalid=mode==="nova"&&(rows.some(r=>(!r.included||r.revisar||r.destino!==r.suggested)&&!r.motivo.trim())||!name.trim());
 async function submit(){setBusy(true);const ok=await onAction(mode==="encerrar"?{action:"encerrar",temporadaId:source,confirmacao:confirm,revision}:{action:"nova",anteriorId:source,nome:name,confirmacao:true,roster:rows.filter(r=>r.included).map(r=>({pilotoId:r.pilotoId,serie:r.destino,motivo:r.motivo})),retirados:Object.fromEntries(excluded.map(r=>[r.pilotoId,r.motivo]))});setBusy(false);if(ok)window.location.reload()}
 return <div className="mt-5 space-y-5">{error&&<p role="alert" className="text-red-300">{error}</p>}
 {!mode?<section className="central-panel"><h2>Gerenciamento de temporadas</h2>{!data&&<p className="py-4">Carregando temporadas…</p>}{data?.seasons.map((s:any)=>{const cycle=s.status!=="ativa"?s.status:s.ciclo;return <article key={s.id} className="flex flex-wrap items-center justify-between gap-4 border-b border-border py-5"><div><h3>{s.nome}</h3><span className="mt-2 inline-block rounded border border-border px-2 py-1 text-sm">{cycle}</span>{s.encerrada_em&&<p className="mt-2 text-sm text-muted-foreground">Classificação oficial congelada em {new Date(s.encerrada_em).toLocaleDateString("pt-BR")}</p>}</div><div className="flex flex-wrap gap-2">{cycle==="ativa"&&<><button disabled={busy} className="central-action central-secondary" onClick={()=>open(s.id,"encerrar")}>Encerrar temporada</button><button className="central-action central-secondary" onClick={()=>{if(window.confirm("Marcar como planejada e suspender lançamento de resultados?"))void onAction({action:"ciclo",temporadaId:s.id,ciclo:"planejada"})}}>Marcar planejada</button></>}{cycle==="planejada"&&<button className="central-action" onClick={async()=>{if(await onAction({action:"ciclo",temporadaId:s.id,ciclo:"ativa"}))window.location.reload()}}>Ativar temporada</button>}{s.encerrada_em&&<button disabled={busy||data.seasons.some((x:any)=>x.temporada_anterior_id===s.id)} className="central-action" onClick={()=>open(s.id,"nova")}>Assistente de nova temporada</button>}{cycle==="encerrada"&&<button className="central-action central-secondary" onClick={()=>onAction({action:"ciclo",temporadaId:s.id,ciclo:"arquivada"})}>Arquivar</button>}</div></article>})}</section>:<section className="central-panel"><button className="central-action central-secondary mb-5" onClick={()=>setMode("")}>Voltar às temporadas</button><h2>{mode==="encerrar"?"Revisar classificação oficial":"Assistente de nova temporada"}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{mode==="encerrar"?"Confira todos os resultados e eventuais etapas pendentes antes de encerrar. O encerramento congela a classificação e bloqueia alterações esportivas nesta temporada.":"Cinco primeiros sobem e cinco últimos descem entre séries adjacentes. Empates e grupos pequenos exigem revisão. A composição só será criada após sua confirmação."}</p>
 {mode==="nova"&&<label className="central-field mt-4">Nome da nova temporada<input value={name} maxLength={100} onChange={e=>setName(e.target.value)} placeholder="Ex.: Temporada 4"/></label>}
 <div className="mt-5 grid gap-3 md:grid-cols-3">{divisions.map(d=>{const count=rows.filter(r=>r.included&&r.destino===d.codigo).length,limit=d.limitePilotos??raceData.competicoes.find(c=>c.id===source)?.pilotosPorSerie;return <div key={d.codigo} className="rounded border border-border p-3"><strong>{d.nome}</strong><p className={limit&&count>limit?"text-red-300":"text-muted-foreground"}>{count} de {limit} vagas</p></div>})}</div>
 <div className="mt-4 space-y-2">{rows.map(r=><article key={r.pilotoId} className="grid items-center gap-3 rounded border border-border p-3 md:grid-cols-[1fr_180px_1fr]"><div><strong>{r.apelido}</strong><p className="text-sm text-muted-foreground">Série {r.serie} · {r.rank}º · {r.total} pts{r.revisar?" · Revisar empate/faixa":""}</p></div>{mode==="nova"?<><label className="central-field">Destino<select value={r.included?r.destino:"retirado"} onChange={e=>patch(r.pilotoId,e.target.value==="retirado"?{included:false}:{included:true,destino:e.target.value})}>{divisions.map(d=><option key={d.codigo} value={d.codigo}>{d.nome}</option>)}<option value="retirado">Não participará</option></select></label><label className="central-field">Motivo / decisão administrativa<input value={r.motivo} onChange={e=>patch(r.pilotoId,{motivo:e.target.value})} placeholder={r.revisar?"Registre o critério de desempate":"Exceção, desistência ou observação"}/></label></>:<p className="text-sm">Descarte: {r.descartado} pts</p>}</article>)}</div>
 {mode==="nova"&&<><section className="mt-5 rounded border border-border p-4"><h3>Substituições e decisões administrativas</h3>{excluded.map(r=>{const candidate=rows.filter(p=>p.included&&p.serie===r.serie&&p.destino===p.serie&&p.pilotoId!==r.pilotoId).sort((a,b)=>a.rank-b.rank)[0];return <div key={r.pilotoId} className="my-3 text-sm"><p>{r.apelido} não participará.{candidate?` Próximo elegível da série de origem: ${candidate.apelido} (${candidate.rank}º).`:"Nenhum próximo elegível na classificação de origem."}</p>{candidate&&<button className="central-action central-secondary mt-2" onClick={()=>patch(candidate.pilotoId,{destino:r.destino,motivo:`Substituição confirmada de ${r.apelido}`})}>Confirmar sugestão: {candidate.apelido}</button>}</div>})}<div className="mt-3 flex flex-wrap gap-3"><select aria-label="Adicionar piloto por decisão administrativa" className="min-h-11 min-w-0 flex-1 border border-border px-3" value={add} onChange={e=>setAdd(e.target.value)}><option value="">Selecionar outro piloto da base</option>{candidates.map(p=><option key={p.id} value={p.id}>{p.apelido}</option>)}</select><button disabled={!add} className="central-action central-secondary" onClick={()=>{const p=candidates.find(p=>p.id===add);if(p){setRows(rs=>[...rs,{pilotoId:p.id,apelido:p.apelido,serie:"—",rank:0,total:0,descartado:0,movimento:"exceção",destino:divisions.at(-1)?.codigo??"",revisar:true,motivo:"",included:true}]);setAdd("")}}}>Adicionar à revisão</button></div></section><p className="mt-4 text-sm text-muted-foreground">A temporada será criada como planejada. Configure as novas datas em Administração → Competições antes de ativá-la.</p></>}
 {mode==="encerrar"?<label className="central-field mt-5">Digite ENCERRAR para confirmar<input value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="off"/></label>:<label className="mt-5 flex min-h-11 items-center gap-3"><input type="checkbox" checked={confirm==="sim"} onChange={e=>setConfirm(e.target.checked?"sim":"")}/>Revisei a composição, as retiradas e as exceções.</label>}
 <button disabled={busy||invalid||(mode==="encerrar"?confirm!=="ENCERRAR":confirm!=="sim")} className="central-action mt-4" onClick={submit}>{busy?"Salvando…":mode==="encerrar"?"Congelar classificação e encerrar":"Confirmar e criar temporada"}</button>
 </section>}</div>
}
